// Auto-generated — DO NOT EDIT
export const audioMap = {
  "Welcome to ShopSmart! A brand new shop has just opened.": "/assets/audio/audio_welcome_to_shopsmart_a_brand_new_shop_has_just_opened.mp3",
  "It has snacks, stationery, and fun toys — all with price tags.": "/assets/audio/audio_it_has_snacks_stationery_and_fun_toys_all_with_price_tags.mp3",
  "Do you know how to pay for things at a shop?": "/assets/audio/audio_do_you_know_how_to_pay_for_things_at_a_shop.mp3",
  "Let us go on a shopping adventure and learn about money!": "/assets/audio/audio_let_us_go_on_a_shopping_adventure_and_learn_about_money.mp3",
  "Have you ever paid for something at a shop before?": "/assets/audio/audio_have_you_ever_paid_for_something_at_a_shop_before.mp3",
  "Do you know the names of the US coins and bills we use?": "/assets/audio/audio_do_you_know_the_names_of_the_us_coins_and_bills_we_use.mp3",
  "What does the word change mean when you go shopping?": "/assets/audio/audio_what_does_the_word_change_mean_when_you_go_shopping.mp3",
  "Let us find out together!": "/assets/audio/audio_let_us_find_out_together.mp3",
  "Sam just opened his shop. Everything has a price tag on it!": "/assets/audio/audio_sam_just_opened_his_shop_everything_has_a_price_tag_on_it.mp3",
  "Look carefully at the prices as you shop.": "/assets/audio/audio_look_carefully_at_the_prices_as_you_shop.mp3",
  "Emma wants to buy a chocolate bar that costs 80 cents.": "/assets/audio/audio_emma_wants_to_buy_a_chocolate_bar_that_costs_80_cents.mp3",
  "Does she have enough coins in her purse?": "/assets/audio/audio_does_she_have_enough_coins_in_her_purse.mp3",
  "Emma has one dollar. She gives it to the shopkeeper Sam.": "/assets/audio/audio_emma_has_one_dollar_she_gives_it_to_the_shopkeeper_sam.mp3",
  "She paid more than the price of 80 cents.": "/assets/audio/audio_she_paid_more_than_the_price_of_80_cents.mp3",
  "Sam gives Emma 20 cents back. That is her change!": "/assets/audio/audio_sam_gives_emma_20_cents_back_that_is_her_change.mp3",
  "Change equals the amount you paid minus the price.": "/assets/audio/audio_change_equals_the_amount_you_paid_minus_the_price.mp3",
  "Let us learn about US coins and bills!": "/assets/audio/audio_let_us_learn_about_us_coins_and_bills.mp3",
  "Tap each coin or bill to hear its name and value.": "/assets/audio/audio_tap_each_coin_or_bill_to_hear_its_name_and_value.mp3",
  "Now let us practise counting coins!": "/assets/audio/audio_now_let_us_practise_counting_coins.mp3",
  "Tap the coins to add them to the tray and count the total.": "/assets/audio/audio_tap_the_coins_to_add_them_to_the_tray_and_count_the_total.mp3",
  "Which piggy bank has more money?": "/assets/audio/audio_which_piggy_bank_has_more_money.mp3",
  "Tap the one with the bigger amount!": "/assets/audio/audio_tap_the_one_with_the_bigger_amount.mp3",
  "Emma wants to buy something from the shop.": "/assets/audio/audio_emma_wants_to_buy_something_from_the_shop.mp3",
  "Does she have enough money to buy it?": "/assets/audio/audio_does_she_have_enough_money_to_buy_it.mp3",
  "Count the coins first, then tap your answer.": "/assets/audio/audio_count_the_coins_first_then_tap_your_answer.mp3",
  "Time to pay at the cash register!": "/assets/audio/audio_time_to_pay_at_the_cash_register.mp3",
  "Choose the right bill, then work out the change you will get.": "/assets/audio/audio_choose_the_right_bill_then_work_out_the_change_you_will_get.mp3",
  "Sam has a word problem for you to solve!": "/assets/audio/audio_sam_has_a_word_problem_for_you_to_solve.mp3",
  "Read the story carefully and choose the correct answer.": "/assets/audio/audio_read_the_story_carefully_and_choose_the_correct_answer.mp3",
  "That is right! Well done!": "/assets/audio/audio_that_is_right_well_done.mp3",
  "Excellent! You are a money expert!": "/assets/audio/audio_excellent_you_are_a_money_expert.mp3",
  "Perfect! Great counting skills!": "/assets/audio/audio_perfect_great_counting_skills.mp3",
  "Brilliant! You got it right!": "/assets/audio/audio_brilliant_you_got_it_right.mp3",
  "Spot on! You really know your money!": "/assets/audio/audio_spot_on_you_really_know_your_money.mp3",
  "Hot streak! You are on fire! Keep going!": "/assets/audio/audio_hot_streak_you_are_on_fire_keep_going.mp3",
  "Money Master! Ten correct in a row! Amazing work!": "/assets/audio/audio_money_master_ten_correct_in_a_row_amazing_work.mp3",
  "Hmm, not quite. Let us try again!": "/assets/audio/audio_hmm_not_quite_let_us_try_again.mp3",
  "Here is a hint to help you. You can do it!": "/assets/audio/audio_here_is_a_hint_to_help_you_you_can_do_it.mp3",
  "You have learned so much about money today!": "/assets/audio/audio_you_have_learned_so_much_about_money_today.mp3",
  "What was your favourite part of the lesson?": "/assets/audio/audio_what_was_your_favourite_part_of_the_lesson.mp3",
  "Tap a thought bubble to share what you learned!": "/assets/audio/audio_tap_a_thought_bubble_to_share_what_you_learned.mp3",
  "Great! I can name US coins and bills!": "/assets/audio/audio_great_i_can_name_us_coins_and_bills.mp3",
  "Great! I can count coins and find the total!": "/assets/audio/audio_great_i_can_count_coins_and_find_the_total.mp3",
  "Great! I know how to check if I have enough money!": "/assets/audio/audio_great_i_know_how_to_check_if_i_have_enough_money.mp3",
  "Great! Money you get back when you pay too much.": "/assets/audio/audio_great_money_you_get_back_when_you_pay_too_much.mp3",
  "Great! 40 cents is the correct change!": "/assets/audio/audio_great_40_cents_is_the_correct_change.mp3",
  "Three stars! You are a true Money Master!": "/assets/audio/audio_three_stars_you_are_a_true_money_master.mp3",
  "Sam and Emma are so proud of you!": "/assets/audio/audio_sam_and_emma_are_so_proud_of_you.mp3",
  "Two stars! Fantastic work today!": "/assets/audio/audio_two_stars_fantastic_work_today.mp3",
  "Keep practising and you will reach three stars next time!": "/assets/audio/audio_keep_practising_and_you_will_reach_three_stars_next_time.mp3",
  "One star — you completed the module! Well done!": "/assets/audio/audio_one_star_you_completed_the_module_well_done.mp3",
  "Try again to improve your score!": "/assets/audio/audio_try_again_to_improve_your_score.mp3",
  "Amazing! You earned the Hot Streak badge! Keep it up!": "/assets/audio/audio_amazing_you_earned_the_hot_streak_badge_keep_it_up.mp3",
  "Amazing! You earned the Money Master badge! Keep it up!": "/assets/audio/audio_amazing_you_earned_the_money_master_badge_keep_it_up.mp3",
  "Amazing! You earned the Shop Explorer badge! Keep it up!": "/assets/audio/audio_amazing_you_earned_the_shop_explorer_badge_keep_it_up.mp3",
  "Amazing! You earned the Coin Expert badge! Keep it up!": "/assets/audio/audio_amazing_you_earned_the_coin_expert_badge_keep_it_up.mp3",
  "Emma is one step closer to becoming a great shopper!": "/assets/audio/audio_emma_is_one_step_closer_to_becoming_a_great_shopper.mp3",
  "Congratulations! You have completed all six stations!": "/assets/audio/audio_congratulations_you_have_completed_all_six_stations.mp3",
  "You are now ready for the test. All the best!": "/assets/audio/audio_you_are_now_ready_for_the_test_all_the_best.mp3",
  "Get ready — 100 questions are coming your way. Let us go!": "/assets/audio/audio_get_ready_100_questions_are_coming_your_way_let_us_go.mp3",
  "What is the value of this US coin?": "/assets/audio/audio_what_is_the_value_of_this_us_coin.mp3",
  "How much money is shown in total?": "/assets/audio/audio_how_much_money_is_shown_in_total.mp3",
  "Which piggy bank has MORE money?": "/assets/audio/audio_which_piggy_bank_has_more_money.mp3",
  "Emma has $3.10 in her wallet. The Bread Loaf costs $3.10. Does she have enough money?": "/assets/audio/audio_emma_has_310_in_her_wallet_the_bread_loaf_costs_310_does_she_have_enough_money.mp3",
  "Emma has $2.95 in her wallet. The Crayons costs $2.70. Does she have enough money?": "/assets/audio/audio_emma_has_295_in_her_wallet_the_crayons_costs_270_does_she_have_enough_money.mp3",
  "Emma has 25¢ in her wallet. The Banana costs 25¢. Does she have enough money?": "/assets/audio/audio_emma_has_25_in_her_wallet_the_banana_costs_25_does_she_have_enough_money.mp3",
  "Emma has 30¢ in her wallet. The Lollipop costs 55¢. Does she have enough money?": "/assets/audio/audio_emma_has_30_in_her_wallet_the_lollipop_costs_55_does_she_have_enough_money.mp3",
  "Emma has $1.30 in her wallet. The Biscuit Pack costs $1.80. Does she have enough money?": "/assets/audio/audio_emma_has_130_in_her_wallet_the_biscuit_pack_costs_180_does_she_have_enough_money.mp3",
  "Emma has $1.05 in her wallet. The Yo-Yo costs $1.05. Does she have enough money?": "/assets/audio/audio_emma_has_105_in_her_wallet_the_yoyo_costs_105_does_she_have_enough_money.mp3",
  "Emma has 95¢ in her wallet. The Bookmark costs 90¢. Does she have enough money?": "/assets/audio/audio_emma_has_95_in_her_wallet_the_bookmark_costs_90_does_she_have_enough_money.mp3",
  "Emma has 85¢ in her wallet. The Ruler costs $1.35. Does she have enough money?": "/assets/audio/audio_emma_has_85_in_her_wallet_the_ruler_costs_135_does_she_have_enough_money.mp3",
  "Emma has 50¢ in her wallet. The Pencil Sharpener costs 55¢. Does she have enough money?": "/assets/audio/audio_emma_has_50_in_her_wallet_the_pencil_sharpener_costs_55_does_she_have_enough_mon.mp3",
  "Emma has $1.55 in her wallet. The Tissue Pack costs $1.55. Does she have enough money?": "/assets/audio/audio_emma_has_155_in_her_wallet_the_tissue_pack_costs_155_does_she_have_enough_money.mp3",
  "Emma has 55¢ in her wallet. The Balloon costs 30¢. Does she have enough money?": "/assets/audio/audio_emma_has_55_in_her_wallet_the_balloon_costs_30_does_she_have_enough_money.mp3",
  "Emma has $1.75 in her wallet. The Juice Box costs $1.25. Does she have enough money?": "/assets/audio/audio_emma_has_175_in_her_wallet_the_juice_box_costs_125_does_she_have_enough_money.mp3",
  "Emma has $1.80 in her wallet. The Sweets Bag costs $1.70. Does she have enough money?": "/assets/audio/audio_emma_has_180_in_her_wallet_the_sweets_bag_costs_170_does_she_have_enough_money.mp3",
  "Emma has $1.15 in her wallet. The Cookie costs 65¢. Does she have enough money?": "/assets/audio/audio_emma_has_115_in_her_wallet_the_cookie_costs_65_does_she_have_enough_money.mp3",
  "Emma has $2.20 in her wallet. The Sandwich costs $2.20. Does she have enough money?": "/assets/audio/audio_emma_has_220_in_her_wallet_the_sandwich_costs_220_does_she_have_enough_money.mp3",
  "Emma has $2 in her wallet. The Tissue Pack costs $2. Does she have enough money?": "/assets/audio/audio_emma_has_2_in_her_wallet_the_tissue_pack_costs_2_does_she_have_enough_money.mp3",
  "Emma has 25¢ in her wallet. The Banana costs 50¢. Does she have enough money?": "/assets/audio/audio_emma_has_25_in_her_wallet_the_banana_costs_50_does_she_have_enough_money.mp3",
  "Emma has $1.40 in her wallet. The Ice Cream costs $1.35. Does she have enough money?": "/assets/audio/audio_emma_has_140_in_her_wallet_the_ice_cream_costs_135_does_she_have_enough_money.mp3",
  "Emma has $1 in her wallet. The Water Bottle costs $1.25. Does she have enough money?": "/assets/audio/audio_emma_has_1_in_her_wallet_the_water_bottle_costs_125_does_she_have_enough_money.mp3",
  "Emma has $1.45 in her wallet. The Water Bottle costs $1.45. Does she have enough money?": "/assets/audio/audio_emma_has_145_in_her_wallet_the_water_bottle_costs_145_does_she_have_enough_money.mp3",
  "Emma has $1.30 in her wallet. The Ruler costs $1.35. Does she have enough money?": "/assets/audio/audio_emma_has_130_in_her_wallet_the_ruler_costs_135_does_she_have_enough_money.mp3",
  "Emma has $1.85 in her wallet. The Biscuit Pack costs $1.90. Does she have enough money?": "/assets/audio/audio_emma_has_185_in_her_wallet_the_biscuit_pack_costs_190_does_she_have_enough_money.mp3",
  "Emma has $2.40 in her wallet. The Notebook costs $2.15. Does she have enough money?": "/assets/audio/audio_emma_has_240_in_her_wallet_the_notebook_costs_215_does_she_have_enough_money.mp3",
  "Emma has $2.90 in her wallet. The Ice Cream costs $2.40. Does she have enough money?": "/assets/audio/audio_emma_has_290_in_her_wallet_the_ice_cream_costs_240_does_she_have_enough_money.mp3",
  "Emma has $1.55 in her wallet. The Water Bottle costs $1.45. Does she have enough money?": "/assets/audio/audio_emma_has_155_in_her_wallet_the_water_bottle_costs_145_does_she_have_enough_money.mp3",
  "Emma has 85¢ in her wallet. The Bookmark costs 90¢. Does she have enough money?": "/assets/audio/audio_emma_has_85_in_her_wallet_the_bookmark_costs_90_does_she_have_enough_money.mp3",
  "Emma has $3.25 in her wallet. The Bread Loaf costs $3. Does she have enough money?": "/assets/audio/audio_emma_has_325_in_her_wallet_the_bread_loaf_costs_3_does_she_have_enough_money.mp3",
  "Emma has 50¢ in her wallet. The Banana costs 50¢. Does she have enough money?": "/assets/audio/audio_emma_has_50_in_her_wallet_the_banana_costs_50_does_she_have_enough_money.mp3",
  "Emma has 40¢ in her wallet. The Apple costs 40¢. Does she have enough money?": "/assets/audio/audio_emma_has_40_in_her_wallet_the_apple_costs_40_does_she_have_enough_money.mp3",
  "Emma has $1.50 in her wallet. The Yo-Yo costs $1.25. Does she have enough money?": "/assets/audio/audio_emma_has_150_in_her_wallet_the_yoyo_costs_125_does_she_have_enough_money.mp3",
  "Emma has 20¢ in her wallet. The Eraser costs 25¢. Does she have enough money?": "/assets/audio/audio_emma_has_20_in_her_wallet_the_eraser_costs_25_does_she_have_enough_money.mp3",
  "Emma has $2.65 in her wallet. The Sandwich costs $2.60. Does she have enough money?": "/assets/audio/audio_emma_has_265_in_her_wallet_the_sandwich_costs_260_does_she_have_enough_money.mp3",
  "Emma has 65¢ in her wallet. The Cookie costs 65¢. Does she have enough money?": "/assets/audio/audio_emma_has_65_in_her_wallet_the_cookie_costs_65_does_she_have_enough_money.mp3",
  "Emma has 45¢ in her wallet. The Lollipop costs 40¢. Does she have enough money?": "/assets/audio/audio_emma_has_45_in_her_wallet_the_lollipop_costs_40_does_she_have_enough_money.mp3",
  "Emma has 75¢ in her wallet. The Lollipop costs 65¢. Does she have enough money?": "/assets/audio/audio_emma_has_75_in_her_wallet_the_lollipop_costs_65_does_she_have_enough_money.mp3",
  "Emma has $2.70 in her wallet. The Ice Cream costs $2.45. Does she have enough money?": "/assets/audio/audio_emma_has_270_in_her_wallet_the_ice_cream_costs_245_does_she_have_enough_money.mp3",
  "Emma buys a Banana for 45¢ and a Cookie for 30¢. She pays with $5. How much change does she get?": "/assets/audio/audio_emma_buys_a_banana_for_45_and_a_cookie_for_30_she_pays_with_5_how_much_change_do.mp3",
  "Emma buys a Chocolate Bar for $1.15. She pays with $5. How much change does she get?": "/assets/audio/audio_emma_buys_a_chocolate_bar_for_115_she_pays_with_5_how_much_change_does_she_get.mp3",
  "Emma buys a Pencil Sharpener for 75¢. She pays with $2. How much change does she get?": "/assets/audio/audio_emma_buys_a_pencil_sharpener_for_75_she_pays_with_2_how_much_change_does_she_get.mp3",
  "Emma buys a Notebook for $2.40. She pays with $10. How much change does she get?": "/assets/audio/audio_emma_buys_a_notebook_for_240_she_pays_with_10_how_much_change_does_she_get.mp3",
  "Emma buys a Biscuit Pack for $1.55 and a Glue Stick for $1.30. She pays with $5. How much change does she get?": "/assets/audio/audio_emma_buys_a_biscuit_pack_for_155_and_a_glue_stick_for_130_she_pays_with_5_how_mu.mp3",
  "Emma buys a Glue Stick for $1.10. She pays with $2. How much change does she get?": "/assets/audio/audio_emma_buys_a_glue_stick_for_110_she_pays_with_2_how_much_change_does_she_get.mp3",
  "Sam wants to buy a Glue Stick that costs $1.50. He has $5. How much money will he have left after buying it?": "/assets/audio/audio_sam_wants_to_buy_a_glue_stick_that_costs_150_he_has_5_how_much_money_will_he_hav.mp3",
  "Sam wants to buy a Notebook that costs $2.10. He has $5. How much money will he have left after buying it?": "/assets/audio/audio_sam_wants_to_buy_a_notebook_that_costs_210_he_has_5_how_much_money_will_he_have_.mp3",
  "Emma buys a Biscuit Pack for $2.35. She gives the shopkeeper $10. How much change does Emma get?": "/assets/audio/audio_emma_buys_a_biscuit_pack_for_235_she_gives_the_shopkeeper_10_how_much_change_doe.mp3",
  "Emma buys a Crayons for $2.10. She gives the shopkeeper $5. How much change does Emma get?": "/assets/audio/audio_emma_buys_a_crayons_for_210_she_gives_the_shopkeeper_5_how_much_change_does_emma.mp3",
  "Emma buys a Cookie for 45¢ and a Bookmark for 95¢. She pays with $5. How much change does she get?": "/assets/audio/audio_emma_buys_a_cookie_for_45_and_a_bookmark_for_95_she_pays_with_5_how_much_change_.mp3",
  "Emma buys a Ice Cream for $2.45. She pays with $10. How much change does she get?": "/assets/audio/audio_emma_buys_a_ice_cream_for_245_she_pays_with_10_how_much_change_does_she_get.mp3",
  "Emma buys a Eraser for 55¢. She pays with $1. How much change does she get?": "/assets/audio/audio_emma_buys_a_eraser_for_55_she_pays_with_1_how_much_change_does_she_get.mp3",
  "Emma buys a Sweets Bag for $1.20. She pays with $10. How much change does she get?": "/assets/audio/audio_emma_buys_a_sweets_bag_for_120_she_pays_with_10_how_much_change_does_she_get.mp3",
  "Sam wants to buy a Water Bottle that costs $1.35. He has $2. How much money will he have left after buying it?": "/assets/audio/audio_sam_wants_to_buy_a_water_bottle_that_costs_135_he_has_2_how_much_money_will_he_h.mp3",
  "Emma buys a Crayons for $1.95. She pays with $2. How much change does she get?": "/assets/audio/audio_emma_buys_a_crayons_for_195_she_pays_with_2_how_much_change_does_she_get.mp3",
  "Emma buys a Glue Stick for $1.05. She pays with $5. How much change does she get?": "/assets/audio/audio_emma_buys_a_glue_stick_for_105_she_pays_with_5_how_much_change_does_she_get.mp3",
  "Emma buys a Sticker Pack for $1.60. She pays with $2. How much change does she get?": "/assets/audio/audio_emma_buys_a_sticker_pack_for_160_she_pays_with_2_how_much_change_does_she_get.mp3",
  "Emma buys a Juice Box for 95¢ and a Apple for 50¢. She pays with $5. How much change does she get?": "/assets/audio/audio_emma_buys_a_juice_box_for_95_and_a_apple_for_50_she_pays_with_5_how_much_change_.mp3",
  "Sam wants to buy a Cookie that costs 45¢. He has $1. How much money will he have left after buying it?": "/assets/audio/audio_sam_wants_to_buy_a_cookie_that_costs_45_he_has_1_how_much_money_will_he_have_lef.mp3",
  "Emma buys a Ice Cream for $1.80. She pays with $5. How much change does she get?": "/assets/audio/audio_emma_buys_a_ice_cream_for_180_she_pays_with_5_how_much_change_does_she_get.mp3",
  "Emma buys a Banana for 50¢. She pays with $5. How much change does she get?": "/assets/audio/audio_emma_buys_a_banana_for_50_she_pays_with_5_how_much_change_does_she_get.mp3",
  "Emma buys a Ice Cream for $1. She gives the shopkeeper $5. How much change does Emma get?": "/assets/audio/audio_emma_buys_a_ice_cream_for_1_she_gives_the_shopkeeper_5_how_much_change_does_emma.mp3",
  "Emma buys a Balloon for 70¢. She gives the shopkeeper $1. How much change does Emma get?": "/assets/audio/audio_emma_buys_a_balloon_for_70_she_gives_the_shopkeeper_1_how_much_change_does_emma_.mp3",
  "Emma buys a Eraser for 50¢. She pays with $10. How much change does she get?": "/assets/audio/audio_emma_buys_a_eraser_for_50_she_pays_with_10_how_much_change_does_she_get.mp3",
  "Emma buys a Sticker Pack for $1.35. She pays with $2. How much change does she get?": "/assets/audio/audio_emma_buys_a_sticker_pack_for_135_she_pays_with_2_how_much_change_does_she_get.mp3",
  "Emma buys a Notebook for $1.05 and a Yo-Yo for $2.45. She pays with $5. How much change does she get?": "/assets/audio/audio_emma_buys_a_notebook_for_105_and_a_yoyo_for_245_she_pays_with_5_how_much_change_.mp3",
  "Emma buys a Toy Car for $3.50. She pays with $5. How much change does she get?": "/assets/audio/audio_emma_buys_a_toy_car_for_350_she_pays_with_5_how_much_change_does_she_get.mp3",
  "Sam wants to buy a Pencil Sharpener that costs 65¢. He has $2. How much money will he have left after buying it?": "/assets/audio/audio_sam_wants_to_buy_a_pencil_sharpener_that_costs_65_he_has_2_how_much_money_will_h.mp3",
  "Sam wants to buy a Crayons that costs $3.45. He has $5. How much money will he have left after buying it?": "/assets/audio/audio_sam_wants_to_buy_a_crayons_that_costs_345_he_has_5_how_much_money_will_he_have_l.mp3",
  "Emma buys a Balloon for 50¢. She pays with $5. How much change does she get?": "/assets/audio/audio_emma_buys_a_balloon_for_50_she_pays_with_5_how_much_change_does_she_get.mp3",
  "Emma buys a Crayons for $2.75 and a Chocolate Bar for $1.45. She pays with $5. How much change does she get?": "/assets/audio/audio_emma_buys_a_crayons_for_275_and_a_chocolate_bar_for_145_she_pays_with_5_how_much.mp3",
  "Emma buys a Water Bottle for $1.50. She pays with $2. How much change does she get?": "/assets/audio/audio_emma_buys_a_water_bottle_for_150_she_pays_with_2_how_much_change_does_she_get.mp3",
  "Emma buys a Juice Box for $1.25. She pays with $2. How much change does she get?": "/assets/audio/audio_emma_buys_a_juice_box_for_125_she_pays_with_2_how_much_change_does_she_get.mp3",
  "Emma buys a Sandwich for $1.55. She pays with $5. How much change does she get?": "/assets/audio/audio_emma_buys_a_sandwich_for_155_she_pays_with_5_how_much_change_does_she_get.mp3",
  "Sam wants to buy a Pencil that costs 35¢. He has $2. How much money will he have left after buying it?": "/assets/audio/audio_sam_wants_to_buy_a_pencil_that_costs_35_he_has_2_how_much_money_will_he_have_lef.mp3",
  "Emma buys a Bookmark for 55¢ and a Bread Loaf for $3.20. She pays with $5. How much change does she get?": "/assets/audio/audio_emma_buys_a_bookmark_for_55_and_a_bread_loaf_for_320_she_pays_with_5_how_much_ch.mp3",
  "Emma buys a Crayons for $1.50 and a Water Bottle for $1. She pays with $5. How much change does she get?": "/assets/audio/audio_emma_buys_a_crayons_for_150_and_a_water_bottle_for_1_she_pays_with_5_how_much_ch.mp3",
  "Sam wants to buy a Cookie that costs 70¢. He has $2. How much money will he have left after buying it?": "/assets/audio/audio_sam_wants_to_buy_a_cookie_that_costs_70_he_has_2_how_much_money_will_he_have_lef.mp3",
  "Emma buys a Notebook for $1.70. She pays with $5. How much change does she get?": "/assets/audio/audio_emma_buys_a_notebook_for_170_she_pays_with_5_how_much_change_does_she_get.mp3",
  "Emma buys a Chocolate Bar for $1.80. She pays with $10. How much change does she get?": "/assets/audio/audio_emma_buys_a_chocolate_bar_for_180_she_pays_with_10_how_much_change_does_she_get.mp3",
  "Emma buys a Glue Stick for 75¢. She pays with $1. How much change does she get?": "/assets/audio/audio_emma_buys_a_glue_stick_for_75_she_pays_with_1_how_much_change_does_she_get.mp3",
  "Emma buys a Pencil for 30¢. She pays with $10. How much change does she get?": "/assets/audio/audio_emma_buys_a_pencil_for_30_she_pays_with_10_how_much_change_does_she_get.mp3",
  "Emma buys a Lollipop for 70¢. She pays with $5. How much change does she get?": "/assets/audio/audio_emma_buys_a_lollipop_for_70_she_pays_with_5_how_much_change_does_she_get.mp3",
  "Emma buys a Muffin for $1.20. She pays with $2. How much change does she get?": "/assets/audio/audio_emma_buys_a_muffin_for_120_she_pays_with_2_how_much_change_does_she_get.mp3",
  "Emma buys a Bread Loaf for $2.05. She gives the shopkeeper $5. How much change does Emma get?": "/assets/audio/audio_emma_buys_a_bread_loaf_for_205_she_gives_the_shopkeeper_5_how_much_change_does_e.mp3",
  "Emma buys a Chocolate Bar for $1.90. She pays with $2. How much change does she get?": "/assets/audio/audio_emma_buys_a_chocolate_bar_for_190_she_pays_with_2_how_much_change_does_she_get.mp3",
  "Emma buys a Muffin for $1.85. She pays with $5. How much change does she get?": "/assets/audio/audio_emma_buys_a_muffin_for_185_she_pays_with_5_how_much_change_does_she_get.mp3",
  "Emma buys a Sandwich for $1.65. She pays with $5. How much change does she get?": "/assets/audio/audio_emma_buys_a_sandwich_for_165_she_pays_with_5_how_much_change_does_she_get.mp3",
  "Sam wants to buy a Juice Box that costs 80¢. He has $1. How much money will he have left after buying it?": "/assets/audio/audio_sam_wants_to_buy_a_juice_box_that_costs_80_he_has_1_how_much_money_will_he_have_.mp3",
  "Emma buys a Ice Cream for $1.05. She pays with $5. How much change does she get?": "/assets/audio/audio_emma_buys_a_ice_cream_for_105_she_pays_with_5_how_much_change_does_she_get.mp3",
  "Emma buys a Sticker Pack for $2.30. She pays with $10. How much change does she get?": "/assets/audio/audio_emma_buys_a_sticker_pack_for_230_she_pays_with_10_how_much_change_does_she_get.mp3",
  "Emma buys a Cookie for 60¢. She pays with $1. How much change does she get?": "/assets/audio/audio_emma_buys_a_cookie_for_60_she_pays_with_1_how_much_change_does_she_get.mp3",
  "Emma buys a Lollipop for 75¢ and a Biscuit Pack for $1.10. She pays with $5. How much change does she get?": "/assets/audio/audio_emma_buys_a_lollipop_for_75_and_a_biscuit_pack_for_110_she_pays_with_5_how_much_.mp3",
  "Emma buys a Sweets Bag for $1.85. She pays with $10. How much change does she get?": "/assets/audio/audio_emma_buys_a_sweets_bag_for_185_she_pays_with_10_how_much_change_does_she_get.mp3",
  "Emma buys a Ruler for $1.05 and a Eraser for 25¢. She pays with $5. How much change does she get?": "/assets/audio/audio_emma_buys_a_ruler_for_105_and_a_eraser_for_25_she_pays_with_5_how_much_change_do.mp3",
  "Emma buys a Juice Box for $1.15 and a Balloon for 45¢. She pays with $5. How much change does she get?": "/assets/audio/audio_emma_buys_a_juice_box_for_115_and_a_balloon_for_45_she_pays_with_5_how_much_chan.mp3",
  "Emma buys a Eraser for 70¢. She pays with $1. How much change does she get?": "/assets/audio/audio_emma_buys_a_eraser_for_70_she_pays_with_1_how_much_change_does_she_get.mp3",
  "Emma buys a Yo-Yo for $2. She pays with $10. How much change does she get?": "/assets/audio/audio_emma_buys_a_yoyo_for_2_she_pays_with_10_how_much_change_does_she_get.mp3",
  "Emma buys a Sandwich for $3.30. She pays with $5. How much change does she get?": "/assets/audio/audio_emma_buys_a_sandwich_for_330_she_pays_with_5_how_much_change_does_she_get.mp3",
  "Sam wants to buy a Banana that costs 45¢. He has $1. How much money will he have left after buying it?": "/assets/audio/audio_sam_wants_to_buy_a_banana_that_costs_45_he_has_1_how_much_money_will_he_have_lef.mp3",
  "Emma buys a Ice Cream for $1.95. She pays with $5. How much change does she get?": "/assets/audio/audio_emma_buys_a_ice_cream_for_195_she_pays_with_5_how_much_change_does_she_get.mp3",
  "Sam wants to buy a Glue Stick that costs 95¢. He has $1. How much money will he have left after buying it?": "/assets/audio/audio_sam_wants_to_buy_a_glue_stick_that_costs_95_he_has_1_how_much_money_will_he_have.mp3",
  "Sam wants to buy a Tissue Pack that costs $1.05. He has $5. How much money will he have left after buying it?": "/assets/audio/audio_sam_wants_to_buy_a_tissue_pack_that_costs_105_he_has_5_how_much_money_will_he_ha.mp3",
  "Sam wants to buy a Sticker Pack that costs $1.90. He has $5. How much money will he have left after buying it?": "/assets/audio/audio_sam_wants_to_buy_a_sticker_pack_that_costs_190_he_has_5_how_much_money_will_he_h.mp3",
  "Emma buys a Cookie for 55¢. She pays with $1. How much change does she get?": "/assets/audio/audio_emma_buys_a_cookie_for_55_she_pays_with_1_how_much_change_does_she_get.mp3",
  "Emma buys a Eraser for 40¢ and a Juice Box for $1. She pays with $5. How much change does she get?": "/assets/audio/audio_emma_buys_a_eraser_for_40_and_a_juice_box_for_1_she_pays_with_5_how_much_change_.mp3",
  "Emma buys a Yo-Yo for $1.80. She gives the shopkeeper $5. How much change does Emma get?": "/assets/audio/audio_emma_buys_a_yoyo_for_180_she_gives_the_shopkeeper_5_how_much_change_does_emma_ge.mp3",
  "Emma buys a Yo-Yo for $2.15. She pays with $5. How much change does she get?": "/assets/audio/audio_emma_buys_a_yoyo_for_215_she_pays_with_5_how_much_change_does_she_get.mp3",
  "Emma buys a Banana for 25¢ and a Balloon for 60¢. She pays with $5. How much change does she get?": "/assets/audio/audio_emma_buys_a_banana_for_25_and_a_balloon_for_60_she_pays_with_5_how_much_change_d.mp3",
  "Emma buys a Sweets Bag for 80¢. She pays with $5. How much change does she get?": "/assets/audio/audio_emma_buys_a_sweets_bag_for_80_she_pays_with_5_how_much_change_does_she_get.mp3",
  "Sam wants to buy a Banana that costs 35¢. He has $2. How much money will he have left after buying it?": "/assets/audio/audio_sam_wants_to_buy_a_banana_that_costs_35_he_has_2_how_much_money_will_he_have_lef.mp3",
  "Emma buys a Glue Stick for $1.25. She gives the shopkeeper $2. How much change does Emma get?": "/assets/audio/audio_emma_buys_a_glue_stick_for_125_she_gives_the_shopkeeper_2_how_much_change_does_e.mp3",
  "Emma buys a Eraser for 75¢ and a Bread Loaf for $3.50. She pays with $5. How much change does she get?": "/assets/audio/audio_emma_buys_a_eraser_for_75_and_a_bread_loaf_for_350_she_pays_with_5_how_much_chan.mp3",
  "Emma buys a Sweets Bag for $1.40. She pays with $2. How much change does she get?": "/assets/audio/audio_emma_buys_a_sweets_bag_for_140_she_pays_with_2_how_much_change_does_she_get.mp3",
  "Emma buys a Tissue Pack for $1.90 and a Muffin for $1.35. She pays with $5. How much change does she get?": "/assets/audio/audio_emma_buys_a_tissue_pack_for_190_and_a_muffin_for_135_she_pays_with_5_how_much_ch.mp3",
  "Emma buys a Yo-Yo for $2.30. She gives the shopkeeper $10. How much change does Emma get?": "/assets/audio/audio_emma_buys_a_yoyo_for_230_she_gives_the_shopkeeper_10_how_much_change_does_emma_g.mp3",
  "Emma buys a Juice Box for 50¢. She gives the shopkeeper $2. How much change does Emma get?": "/assets/audio/audio_emma_buys_a_juice_box_for_50_she_gives_the_shopkeeper_2_how_much_change_does_emm.mp3",
  "Emma buys a Sticker Pack for 75¢. She pays with $5. How much change does she get?": "/assets/audio/audio_emma_buys_a_sticker_pack_for_75_she_pays_with_5_how_much_change_does_she_get.mp3",
  "Emma buys a Muffin for $1.70. She pays with $5. How much change does she get?": "/assets/audio/audio_emma_buys_a_muffin_for_170_she_pays_with_5_how_much_change_does_she_get.mp3",
  "Emma buys a Ruler for $1.40 and a Toy Car for $4.95. She pays with $10. How much change does she get?": "/assets/audio/audio_emma_buys_a_ruler_for_140_and_a_toy_car_for_495_she_pays_with_10_how_much_change.mp3",
  "Emma buys a Lollipop for 40¢. She gives the shopkeeper $1. How much change does Emma get?": "/assets/audio/audio_emma_buys_a_lollipop_for_40_she_gives_the_shopkeeper_1_how_much_change_does_emma.mp3"
};
